# .gitpod.yml

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: next install
    command: yarn add next react react-dom

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
